module.exports = [
    'Action',
    'Adventure',
    'Animated',
    'Art Film',
    'Buddy Cop',
    'Black Comedy',
    'Comedy',
    'Comic Book-Based',
    'Crime',
    'Cyberpunk',
    'Disaster',
    'Drama',
    'Experimental',
    'Fantasy',
    'Historical',
    'Holiday',
    'Military',
    'Musical',
    'Mystery',
    'Horror',
    'Post-Apocalyptic',
    'Romance',
    'Rom-Com',
    'Satire',
    'Science Fiction',
    'Spy',
    'Steampunk',
    'Superhero',
    'Thriller',
    'TV Show-Based',
    'Video Game-Based',
    'Western',
    'Other'
]