module.exports = [
    'Action',
    'Adventure',
    'Animated',
    'Anthology',
    'Apocalytpic',
    'Art Film',
    'Biographical',
    'Black Comedy',
    'Blaxploitation',
    'Buddy Cop',
    'Comedy',
    'Comic Book-Based',
    'Crime',
    'Cyberpunk',
    'Dance',
    'Disaster',
    'Documentary',
    'Drama',
    'Dystopian',
    'Epic',
    'Erotic',
    'Experimental',
    'Family',
    'Fantasy',
    'Gothic',
    'Historical',
    'Holiday',
    'Horror',
    'Independent',
    'Kaiju',
    'Made-For-Television',
    'Martial Arts',
    'Medieval',
    'Military',
    'Monster',
    'Musical',
    'Mystery',
    'Neo-Noir',
    'Post-Apocalyptic',
    'Psychological',
    'Pulp-Noir',
    'Romance',
    'Rom-Com',
    'Satire',
    'Science Fiction',
    'Silent',
    'Slapstick',
    'Slasher',
    'Space Opera',
    'Sport',
    'Spy',
    'Steampunk',
    'Superhero',
    'Supernatural',
    'Suspense',
    'Teen',
    'Thriller',
    'TV Show-Based',
    'Vampire',
    'Video Game-Based',
    'War',
    'Western',
    'Other'
]