module.exports = [
    'Nathan Freeman',
    'Sujan Trivedi',
    'Stephanie Weitzner',
    'Nigam Trivedi',
    'Walter J. McMath',
    'John Vennema',
    'Katharine Croke',
    'Paul Ziemba',
    'Emily Ziemba',
    'Carmen Roman',
    'Ben Beckley-Chayes',
    'Jeffrey Kitrosser',
    'Salman Baig',
    'Jeremy Weissmann',
    'Micah Baskir',
    'Brain Trust',
    'Ziemba Household',
    'Clay Hayles',
    'Lauren Berger',
    'Neal Tillery'
]